steps:
  - name: docker-build-dev
    image: woodpeckerci/plugin-docker-buildx:6.0.3
    settings:
      debug: true
      repo: harbor.crystalnet.org/library/jellyfin
      logins:
      - registry: https://harbor.crystalnet.org/
        username: robot$library+woodpecker
        password:
          from_secret: harbor_token
      registry: harbor.crystalnet.org
      tags: dev
      dockerfile: Dockerfile
      platforms: linux/amd64,linux/arm64,linux/arm/v7
      dry_run: false
when:
  branch: ${CI_REPO_DEFAULT_BRANCH}
  event: push
